apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        environment: development
    spec:
      containers:
        - name: backend
          image: runstackregistry.azurecr.io/backend-dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"
            - name: FLASK_DEBUG
              value: "true"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DB_PATH
              value: "/data/dev_products.db"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
