version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BASE_URL=http://localhost:5000

  db-init:
    build:
      context: ./backend
    command: python db.py -a
    depends_on:
      - backend
    volumes:
      - ./backend:/app
    restart: "no"
