apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prod-ghcr
  namespace: default
  labels:
    app: frontend-prod
    source: github-packages
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-prod
      source: github-packages
  template:
    metadata:
      labels:
        app: frontend-prod
        source: github-packages
    spec:
      nodeSelector:
        kubernetes.azure.com/agentpool: main
      containers:
      - name: frontend
        image: ghcr.io/roman-zvir/frontend-prod:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-prod-ghcr-service
  namespace: default
  labels:
    app: frontend-prod
    source: github-packages
spec:
  selector:
    app: frontend-prod
    source: github-packages
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP
