apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    environment: production
spec:
  replicas: 2  # More replicas for production
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        environment: production
    spec:
      containers:
        - name: backend
          image: developmentbranch.azurecr.io/backend-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
            - name: FLASK_DEBUG
              value: "false"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DB_PATH
              value: "/data/products.db"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
