apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    environment: production
spec:
  replicas: 2  # More replicas for production
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        environment: production
    spec:
      nodeSelector:
        kubernetes.azure.com/agentpool: main
      containers:
        - name: frontend
          image: runstackregistry.azurecr.io/frontend-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BASE_URL
              value: "https://runstack.pp.ua/api"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
