apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  annotations:
    cloud.google.com/neg: '{"ingress": false}'
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
  type: NodePort
