apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudflare-ingress
  annotations:
    # Allow HTTP traffic (Cloudflare will handle HTTPS termination)
    kubernetes.io/ingress.allow-http: "true"
    # Use GCE ingress class
    kubernetes.io/ingress.class: "gce"
    # Reserve the static IP
    kubernetes.io/ingress.global-static-ip-name: "app-static-ip"
    # Add backend timeout for API calls
    cloud.google.com/backend-config: '{"default": "backend-config"}'
spec:
  ingressClassName: "gce"
  rules:
    - host: roman-zvir-pet-project.pp.ua
      http:
        paths:
          # Backend API routes (must come first - more specific)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          # Frontend routes (catch-all)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backend-config
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
