apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    # Azure Load Balancer annotations
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "MC_myResourceGroup_myAKSCluster_eastus"
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  # Uncomment and specify your static IP address here
  # loadBalancerIP: "YOUR_STATIC_IP_ADDRESS"
