apiVersion: apps/v1
k            - name: REACT_APP_API_URL
              value: "https://runstack.pp.ua/api"d: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: developmentbranch.azurecr.io/frontend-dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BASE_URL
              value: "https://runstack.pp.ua/api"
