apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    # Reserve a static IP for the ingress
    kubernetes.io/ingress.global-static-ip-name: "app-static-ip"
    # Enable Google-managed SSL certificate
    networking.gke.io/managed-certificates: "app-ssl-cert"
    # Allow HTTP initially, will redirect to HTTPS once SSL is ready
    kubernetes.io/ingress.allow-http: "true"
spec:
  ingressClassName: "gce"
spec:
  rules:
    # Main domain
    - host: roman-zvir-pet-project.pp.ua
      http:
        paths:
          # Frontend routes
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          # Backend API routes
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
    # Optionally add www subdomain
    - host: www.roman-zvir-pet-project.pp.ua
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
  # For HTTPS (you'll need to set up SSL certificates)
  tls:
    - hosts:
        - roman-zvir-pet-project.pp.ua
        - www.roman-zvir-pet-project.pp.ua
      secretName: app-tls-secret
