name: Docker Build (Fallback)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker-fallback:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image (fallback)
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest

      - name: Build and push frontend image (fallback)
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest
